services:
  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_HOST: db
      DB_NAME: auth_db
      DB_PASS: postgres
      DB_PORT: 5432
      JWT_SECRET: mysecret
    volumes:
      - .:/app
      - /app/node_modules
    command: [ "sh", "-c", "node migrate.js && node server.js" ]

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
